name: Update Football Matches

on:
  workflow_dispatch:

  schedule:
    - cron: "*/15 * * * *"

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get football matches
        env:
          FOOTBALL_API_TOKEN: ${{ secrets.FOOTBALL_API_TOKEN }}
        run: |
          curl \
            -H "X-Auth-Token: $FOOTBALL_API_TOKEN" \
            "https://api.football-data.org/v4/matches" \
            -o api/matches.json

      - name: Check JSON
        run: |
          python -m json.tool api/matches.json > /dev/null

      - name: Commit updated matches
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add api/matches.json

          git diff --cached --quiet || \
          git commit -m "Update football matches"

          git push
